<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\employee.html">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>employee.cs</LastGenOutput>
    </Content>
    <Content Update="wwwroot\employee.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>employee.html</DependentUpon>
    </Content>
    <Content Update="wwwroot\index2.html">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>index2.cs</LastGenOutput>
    </Content>
    <Content Update="wwwroot\index2.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>index2.html</DependentUpon>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

</Project>
